language: node_js
node_js:
    - "0.10"

before_script:
    - npm install -g grunt-cli@0.1.x
    - npm install --quiet
    - npm install -g mocha
    - npm install -g istanbul
    - npm install -g bower
    - bower install

script:
    - grunt
    
after_script:
    - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --timeout 10000 --recursive 
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
